# Generated by Django 2.2 on 2020-02-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(auto_now_add=True)),
                ('plan', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
