# Generated by Django 2.2 on 2020-02-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0002_auto_20200221_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
