# Generated by Django 2.2 on 2020-02-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_app', '0003_remove_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.CharField(max_length=50),
        ),
    ]
